[package]
name = "assets_manager"
version = "0.2.0"
authors = ["Benoît du Garreau"]
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"
description= "Conveniently load, store and cache external resources"

repository = "https://github.com/a1phyr/assets_manager"
documentation = "https://docs.rs/assets_manager"

categories = ["caching", "filesystem", "game-development"]
keywords = ["asset", "assets", "cache", "resources"]


[features]
hot-reloading = ["notify", "log"]

bincode = ["serde_bincode", "serde"]
cbor = ["serde_cbor", "serde"]
json = ["serde_json", "serde"]
msgpack = ["serde_msgpack", "serde"]
ron = ["serde_ron", "serde"]
yaml = ["serde_yaml", "serde"]
toml = ["serde_toml", "serde"]


[dependencies]
parking_lot = {version = "0.10", optional = true}
hashbrown = {version = "0.7", optional = true}

log = {version = "0.4", optional = true}
notify = {version = "4.0", optional = true}

serde = {version = "1.0", optional = true}
serde_bincode = {version = "1.2", package = "bincode", optional = true}
serde_cbor = {version = "0.11", optional = true}
serde_json = {version = "1.0", optional = true}
serde_msgpack = {version = "0.14", package = "rmp-serde", optional = true}
serde_ron = {version = "0.5", package = "ron", optional = true}
serde_toml = {version = "0.5", package = "toml", optional = true}
serde_yaml = {version = "0.8", optional = true}


[dev-dependencies]
cfg-if = "0.1"
rand = "0.7"
serde = {version = "1.0", features = ["derive"]}


[[example]]
name = "basic"
required-features = ["bincode"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
