[package]
name = "assets_manager_macros"
version = "0.1.0"
authors = ["Benoît du Garreau <bdgdlm@outlook.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = {version = "1.0", default-features = false, features = ["parsing", "proc-macro"]}
