on: [push, pull_request]

name: CI

env:
  CARGO_INCREMENTAL: 0

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - 1.51
    steps:
      - name: Install development libraries
        run: sudo apt update && sudo apt install libasound2-dev -y

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Downgrade cpal to MSRV
        if: ${{ matrix.rust }} == "1.51"
        run: cargo update -p cpal --precise 0.13.4

      - name: cargo test
        run: cargo test

      - name: cargo test --all-features
        run: cargo test --all-features

  fmt:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: cargo fmt -- --check
        run: cargo fmt -- --check
