on: [push, pull_request]

name: CI

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - 1.51
    steps:
      - name: Install development libraries
        run: sudo apt install libasound2-dev -y

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true

      - name: cargo test
        run: cargo test

      - name: cargo test --all-features
        run: cargo test --all-features
